---
title:  "IE360 - Spring 2022, Project"
author: "Ahmet Yiğit Doğan, Emre Burak Baş, Sercan Böçkün"
date:   "21 May, 2022"
output: 
    html_document:
        toc: true
        toc_depth: 2
        number_sections: true
        toc_float: true
        fig_caption: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(  message     = FALSE,
	                    warning     = FALSE,
                        fig.align   = "center")
```

# Library Imports and Data Preprocessing

The mainly used libraries in the code are *"forecast"*, *"ggplot2"*, and *"tidyverse"*, along with several supplementary ones. The time series are stored as *"data.frame"* objects.

```{r toolbox-and-data}

# Library imports

require(data.table)
require(tidyverse)
require(lubridate)
require(forecast)
require(ggplot2)
require(GGally)
require(dplyr)
require(MLmetrics)

# Setting the working directory

setwd(getwd())

# Importing the weather data

weather_data <- read.csv("long_weather.csv")

weather_data <- data.table(weather_data)

weather_data <- dcast(weather_data,
                      date + hour ~ variable + lat + lon,
                      value.var = "value")

weather_data[,datetime:=ymd(date) + dhours(hour)]

weather_data <- subset(weather_data, select = -c(date, hour))

# Importing the production data

prod_data <- read.csv("production.csv")

prod_data <- data.table(prod_data)

prod_data[,datetime:=ymd(date) + dhours(hour)]

prod_data <- subset(prod_data, select = -c(date))

data <- full_join(x     = prod_data,
                  y     = weather_data,
                  by    = "datetime")

head(data)

data_r <- data  # Storing a copy for the regular hours model

```

# Checking the Time Series

```{r essential-time-series, fig.show="hold", out.width="50%", fig.cap="Figure 1. Essential Time Series"}

ggplot(data, aes(x = datetime,y = production))  +
    
    geom_line()                                 +
    
    xlab("Date")                                +
    
    ylab("Production (in MwH)")

```

```{r hourly-check}
# Checking the hourly average production rates

round(aggregate(data$production, list(data$hour), FUN = mean), 4)

```

# Model Building

```{r classified-hours, fig.show="hold", out.width="50%"}

# Classified-hours model

# The point is partitioning the data set into three subsets, two of which have non-zero production rates. Two separate models will be built based on these two subsets.

# Critical hours

critical_hours      <- data %>%
    
    filter(hour %in% c(5, 6, 19))

critical_hours$hour <- as.factor(critical_hours$hour)

# Plot

critical_hours %>%
    
    ggplot( aes(x       = datetime,
                y       = production,
                group   = hour,
                color   = hour))                                +
    
    scale_color_manual(name = "Hour",
                       labels = c("5 AM", "6 AM", "7 PM"),
                       values = c("#E64B35B2",
                                  "#3C5488B2",
                                  "#7E6148B2"))                 +
    
    xlab("Date")                                                +
    
    ylab("Production")                                          +
    
    
    
    geom_line()

```

```{r hour-based, fig.show="hold", out.width="50%"}

# Usual hours

usual_hours         <- data %>%
    
    filter(!hour %in% c(0, 1, 2, 3, 4,
                        5, 6, 19,
                        21, 22, 23))

usual_hours$hour    <- as.factor(usual_hours$hour)

# Plot

usual_hours %>%
    
    ggplot( aes(x       = datetime,
                y       = production,
                group   = hour,
                color   = hour)) +
    
    geom_line()

```


```{r critical-hours-nonzero-periods}

# Critical hours

# 5

five_am_nonzero <- critical_hours %>%
    
    filter(hour == "5" & production != 0)

five_am_nonzero_months <- unique(month(five_am_nonzero$datetime))

# 6

six_am_nonzero <- critical_hours %>%
    
    filter(hour == "6" & production != 0)

six_am_nonzero_weeks <- unique(week(six_am_nonzero$datetime))

# 19

seven_pm_nonzero <- critical_hours %>%
    
    filter(hour == "19" & production != 0)

seven_pm_nonzero_weeks <- unique(week(seven_pm_nonzero$datetime))

```


```{r critical-hours-five-am, fig.show="hold", out.width="50%"}

# Models for critical hours

# 5 O'Clock

five_am <- critical_hours %>%
    
    filter(hour == "5")
    
five_am <- subset(five_am, select = -c(hour))
    
# Is in nonzero period? If so, insert the # of the month, else, insert "No".

five_am$is_in_nzp       <- ifelse(month(five_am$datetime) %in% five_am_nonzero_months,
                                  as.factor(month(five_am$datetime)),
                                  "No")

model_five_am <- lm(production~. -datetime,
                    data = five_am)

checkresiduals(model_five_am$residuals)

```

```{r 5-am-lagged, fig.show="hold", out.width="50%"}

five_am$three_days_lag  <- usual_hours[,.(three_days_lag = shift(five_am$production, 
                                                                 n = 3L, 
                                                                 fill = NA, 
                                                                 type = "shift"))]

model_five_am <- lm(production~. -datetime,
                    data = five_am) 

summary(model_five_am)

checkresiduals(model_five_am$residuals)

```


```{r critical-hours-six-am, fig.show="hold", out.width="50%"}

# 6 O'Clock

six_am <- critical_hours %>%
    
    filter(hour == "6")
    
six_am <- subset(six_am, select = -c(hour))

six_am$is_in_nzp <- ifelse(week(six_am$datetime) %in% six_am_nonzero_weeks, 
                           as.factor(week(six_am$datetime)), 
                           "No")

six_am$three_days_lag <- usual_hours[,.(three_days_lag = shift(six_am$production, 
                                                               n = 3L, 
                                                               fill = NA, 
                                                               type = "shift"))]

model_six_am <- lm(production~. -datetime,
                   data = six_am) 

summary(model_six_am)

checkresiduals(model_six_am$residuals)

```

```{r critical-hours-eight-pm, fig.show="hold", out.width="50%"}

# 19 O'Clock

seven_pm <- critical_hours %>%
    
    filter(hour == "19")
    
seven_pm <- subset(seven_pm, select = -c(hour))

seven_pm$is_in_nzp <- ifelse(week(seven_pm$datetime) %in% seven_pm_nonzero_weeks, 
                             as.factor(week(seven_pm$datetime)), 
                             "No")

seven_pm$three_days_lag <- usual_hours[,.(three_days_lag = shift(seven_pm$production, 
                                                                 n = 3L, 
                                                                 fill = NA, 
                                                                 type = "shift"))]
    
model_seven_pm <- lm(production~. -datetime,
                     data = seven_pm) 

summary(model_seven_pm)

checkresiduals(model_seven_pm$residuals)

```


```{r predictions-five-am}

# Prediction 5

pred5 <- data
pred5$is_in_nzp <- ifelse(month(pred5$datetime) %in% five_am_nonzero_months,
                          as.factor(month(pred5$datetime)),
                          "No")

pred5 <- subset(pred5, select = -c(hour))

five_am_ext <- rbind(five_am,
                     pred5[pred5$datetime == "2022-06-03 08:00:00"], # + 3 hours due to lag
                     fill = TRUE)

five_am_ext$three_days_lag <- five_am_ext[,.(three_days_lag = shift(five_am_ext$production, 
                                                                    n = 3L, 
                                                                    fill = NA, 
                                                                    type = "shift"))]

five_am_ext$predictions <- predict(model_five_am, five_am_ext)

results5 <- subset(five_am_ext, select = c("production", "datetime", "predictions"))

```

```{r predicitions-six-am}

# Prediction 6

pred6 <- data
pred6$is_in_nzp <- ifelse(week(pred6$datetime) %in% six_am_nonzero_weeks,
                         as.factor(week(pred6$datetime)),
                         "No")

pred6 <- subset(pred6, select = -c(hour))

six_am_ext <- rbind(six_am, pred6[pred6$datetime == "2022-06-03 09:00:00"], fill = TRUE)

six_am_ext$three_days_lag      <- six_am_ext[,.(three_days_lag = shift(six_am_ext$production, 
                                                                       n = 3L, 
                                                                       fill = NA, 
                                                                       type = "shift"))]

six_am_ext$predictions <- predict(model_six_am, six_am_ext)

results6 <- subset(six_am_ext, select = c("production", "datetime", "predictions"))

```

```{r predictions-seven-pm}

# Prediction 19

pred19 <- data

pred19$is_in_nzp <- ifelse(week(pred19$datetime) %in% seven_pm_nonzero_weeks,
                           as.factor(week(pred19$datetime)),
                           "No")

pred19 <- subset(pred19, select = -c(hour))

seven_pm_ext <- rbind(seven_pm, pred19[pred19$datetime == "2022-06-03 22:00:00"], fill = TRUE)

seven_pm_ext$three_days_lag <- seven_pm_ext[,.(three_days_lag = shift(seven_pm_ext$production, 
                                                                      n = 3L, 
                                                                      fill = NA, 
                                                                      type = "shift"))]

seven_pm_ext$predictions <- predict(model_seven_pm, seven_pm_ext)

results19 <- subset(seven_pm_ext, select = c("production", "datetime", "predictions"))

```

```{r hours-and-months}

# Model for regular hours

data_r[,hour:=hour(datetime)]
data_r[,month:=month(datetime)]

train_data <- copy(data_r)
train_data <- train_data %>% 
    filter((train_data$hour < 19) & (train_data$hour > 6))

train_data$hour     <- as.factor(train_data$hour)
train_data$month    <- as.factor(train_data$month)

```

```{r usual-hours-model}

model_regular <- lm(production~. -datetime, train_data) 

summary(model_regular)

```

```{r fig.show="hold", out.width="50%"}

checkresiduals(model_regular$residuals)

acf(model_regular$residuals, 36)

```

```{r}

# One might try adding 72 hour lagged production as a predictor.
# This corresponds to 36 lag in the training data.
# Normally 24 hour lagged version should be added. Not possible due to restricted data:
# HUGE IMPROVEMENT

train_data$yesterday_prod <- train_data[ , .(yesterday_prod = shift(train_data$production,
                                                                    n = 36L,
                                                                    fill = NA))]

#data$yesterday_1lag_prod = data[,.(yesterday_prod = shift(data$production, n=24L, fill=NA))]

model_regular <- lm(production~. -datetime, train_data)

summary(model_regular)

```

```{r fig.show="hold", out.width="50%"}

checkresiduals(model_regular$residuals)
acf(model_regular$residuals, 2400)

```

```{r}

real_data <- data

real_data$yesterday_prod <- real_data[ , .(yesterday_prod = shift(real_data$production,
                                                                  n = 72L,
                                                                  fill = NA))]

real_data <- real_data %>% filter((real_data$hour < 18) & (real_data$hour > 6))

head(real_data)

```

```{r predictions}

input_data <- (real_data[date(real_data$date) == "2022-06-03"])

input_data$yesterday_prod   <- real_data[date(real_data$date) == "2022-05-31"]$production

input_data$hour             <- as.factor(input_data$hour)

input_data$month            <- as.factor(month((input_data$datetime)))

predictions                 <- input_data[ , predictions:= predict(model_regular,
                                                                   input_data)      ]

```

```{r predictions-vs-real, , fig.show="hold", out.width="50%"}

# Data for the predictions vs real data plot

data_pr_p           <- data

data_pr_p$hour      <- as.factor(data_pr_p$hour)

data_pr_p$month     <- as.factor(month((data_pr_p$datetime)))

data_pr_p$yesterday_prod <- data_pr_p[ , .(yesterday_prod = shift(data_pr_p$production,
                                                                  n = 72L,
                                                                  fill = NA))]

reg_train <- data_pr_p[data_pr_p$hour %in% c("7", "8", "9", "10",
                                            "11", "12", "13", "14",
                                            "15", "16", "17", "18"), ]

reg_train$predicted <- predict(model_regular, reg_train)

regular_results     <- subset(reg_train, select = c(datetime,
                                                    predicted))

data_pr_p <- left_join( x   = data_pr_p,
                        y   = results5[ ,-1],
                        by  = "datetime"    )

data_pr_p <- left_join( x   = data_pr_p,
                        y   = results6[ ,-1],
                        by  = "datetime"    )

data_pr_p <- left_join( x   = data_pr_p,
                        y   = results19[ ,-1],
                        by  = "datetime"        )

data_pr_p <- left_join( x   = data_pr_p,
                        y   = regular_results,
                        by  = "datetime"        )

data_pr_p$predictions <- coalesce(  data_pr_p$predictions.x,
                                    data_pr_p$predictions.y,
                                    data_pr_p$predictions,
                                    data_pr_p$predicted     )

data_pr_p[data_pr_p$hour %in% c("0", "1", "2", "3", "4",
                                "20", "21", "22", "23"),
          c("predicted")]                                   <- 0

data_pr_p[data_pr_p$predicted < 0, c("predicted")]          <- 0

ggplot(data_pr_p, aes(x = datetime)     )   +
    
    geom_line(aes(y = production,
                  color='real',
                  group = 1)            )   + 
    
    geom_line(aes(y = predicted,
                  color = 'predictions',
                  group = 1)            )   +
    
    xlab("Date")                            +
    
    ylab("Production (in MwH)")

```


$~$
